### PR TITLE
Fix Dpad Ocarina L Btn & GI Dpad Stuff

### LINKED ISSUE #544: Ocarina songs that don't use the A button aren't cancelled by L button when playing with D-pad ocarina
Reported by Master L on Discord
Currently, when playing the ocarina with the D-pad using the D-pad ocarina option, holding the L button doesn't properly prevent song recognition _if_ the song doesn't use the A button (Song of Soaring, for example). Songs that use the A button are not affected by this.
This issue doesn't occur when playing the ocarina with the buttons that are mapped to the C button inputs

### PR DESCRIPTION
**Pull request by inspectredc**
Tried Following the Pattern from #441 Here

This should fix #544 

Few thoughts on my part:

- Can we cache the Cvar Result for each frame and reset them?
- Can this work as a hook which sets a bool only changing it when the cvar changes?
- Are Cvars expensive enough that the points above would make sense?

### Build Artifacts
  - [2ship-linux.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/1543736588.zip)
  - [2ship-windows.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/1543747405.zip)
  - [2ship-mac.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/1543870590.zip)

### CODE REVIEW

File: mm/2s2h/Enhancements/GameInteractor/GameInteractor.cpp [hunk 1]
```diff
@@ -230,3 +230,22 @@ int GameInteractor_InvertControl(GIInvertType type) {
 
     return result;
 }
+
+uint32_t GameInteractor_Dpad(GIDpadType type, uint32_t buttonCombo) {
```
Comment (garrettjoecox) [inline mm/2s2h/Enhancements/GameInteractor/GameInteractor.cpp:234]: So what I had in mind here was more generic than being specific to just dpad, but to just controls in general. For instance, you call `GameInteractor_Btn(GI_BTN_OCARINA_UP)`, and a player could opt in to using their dpad, or even right stick to count as "OCARINA_UP".

Does that make sense? Also not sold on the name `GI_BTN`, just an example

Comment (inspectredc) [reply mm/2s2h/Enhancements/GameInteractor/GameInteractor.cpp:234]: I think sticks and buttons are a bit too different to handle them like that honestly but I get the generalisation yea.

Comment (garrettjoecox) [reply mm/2s2h/Enhancements/GameInteractor/GameInteractor.cpp:234]: I want to revisit this, but when we know more / have a better idea

**Review by garrettjoecox — APPROVED** [review]

File: mm/2s2h/Enhancements/GameInteractor/GameInteractor.cpp (hunk 1 above)
Comment (inspectredc) [reply mm/2s2h/Enhancements/GameInteractor/GameInteractor.cpp:234]: Yea sure, do you think I should make a separate PR with the fix?

Comment (inspectredc) [reply mm/2s2h/Enhancements/GameInteractor/GameInteractor.cpp:234]: oh wait nvm ur approving
