### PR TITLE
Fix the check for preventing a HESS crash.

### LINKED ISSUE #645: Wierdshot Crash when HESS/Wierdshot crash prevention is enabled.
### Description of the crash:
Failed a wierdshot input, game crashed. Did it twice today, pretty sure I just didn't untarget Z fast enough.

### Can you reproduce? If so please list the steps:
- [ X] No, I cannot reproduce this crash
- [ ] Yes, here are the steps to reproduce the crash:

 sorry it's not very helpful but this is a visual of the frame the game crashed.
image

### Logs:
[2 Ship 2 Harkinian.log](https://github.com/user-attachments/files/15526243/2.Ship.2.Harkinian.log)

### System Information:
- OS: Windows 11
- GFX Backend: OpenGL
- Game Version: 1.0
- Rom Version:  N64 USA release

### Additional Information:

Yes, I did make sure I had HESS crash fix enabled for both times. Playing on the 1.0 release, didn't see this get fixed in the patch notes but thought I'd share. I'm updating to the newer version now.

### PR DESCRIPTION
**Pull request by louist103**
Fixes #645
Unfortunately I am not good at this game so I can't easily test this and will need someone who is good to try it. 

### Build Artifacts
  - [2ship-linux.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/1629509180.zip)
  - [2ship-mac.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/1629510877.zip)
  - [2ship-windows.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/1629512868.zip)

### CODE REVIEW

File: mm/src/code/z_player_lib.c [hunk 1]
```diff
@@ -2359,7 +2359,7 @@ s32 Player_OverrideLimbDrawGameplayDefault(PlayState* play, s32 limbIndex, Gfx**
 
                 if (handIndex != 0) {
                     handIndex = (handIndex >> 12) - 1;
-                    if (handIndex >= 2) {
+                    if (handIndex > 1) {
```
Comment (inspectredc) [inline mm/src/code/z_player_lib.c]: Not sure this really needs to be changed since it's equivalent and it'll just be easier to keep the same as in decomp

Comment (louist103) [reply mm/src/code/z_player_lib.c]: I guess player does use the >= style. I can change it back.

**Review by Archez — APPROVED** [review]

**Comment by louist103** [comment]
Tested it with goron missile which is much easier to get a HESS out of than a bomb.
