### PR TITLE
Fix GC Warning Labels

### LINKED ISSUE #514: GC US Copy/Erase Textures Bugged
Likely needs to have similar treatment to #442 
copyerasebug

### PR DESCRIPTION
**Pull request by inspectredc**
Fixes #514 based on matching decomp function here https://decomp.me/scratch/IqAhq

Textures were changed from ia8 to ia4 between n64 us and gc us so the load block call's size needed to be adjusted

### CODE REVIEW

File: mm/src/overlays/gamestates/ovl_file_choose/z_file_choose_NES.c [hunk 1]
```diff
@@ -1832,9 +1833,15 @@ void FileSelect_DrawWindowContents(GameState* thisx) {
...
         gDPSetPrimColor(POLY_OPA_DISP++, 0, 0, 255, 255, 255, this->emptyFileTextAlpha);
         gDPSetEnvColor(POLY_OPA_DISP++, 0, 0, 0, 0);
-        gDPLoadTextureBlock(POLY_OPA_DISP++, sWarningLabels[this->warningLabel], G_IM_FMT_IA, G_IM_SIZ_8b, 128, 16, 0,
-                            G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD,
-                            G_TX_NOLOD);
+        if (ResourceMgr_GetGameVersion(0) == MM_NTSC_US_GC) {
+            gDPLoadTextureBlock_4b(POLY_OPA_DISP++, sWarningLabels[this->warningLabel], G_IM_FMT_IA, 128, 16, 0,
+                                   G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMASK, G_TX_NOMASK,
+                                   G_TX_NOLOD, G_TX_NOLOD);
+        } else { // MM_NTSC_US_10
```
Comment (garrettjoecox) [inline mm/src/overlays/gamestates/ovl_file_choose/z_file_choose_NES.c:1840]: is this the general pattern we want to follow, always falling back to US 1.0 for newly supported versions? 

Eg if I added support for another version tomorrow and forgot to add a handler case here, is it more dangerous to run the US 1.0 code, or not run any version's ?

Comment (inspectredc) [reply mm/src/overlays/gamestates/ovl_file_choose/z_file_choose_NES.c:1840]: I feel like it makes it easier to not miss honestly, I don't think either is particularly dangerous though. From what I've decomped of other versions, they all follow the MM_NTSC_US_10 pattern anyway

**Review by garrettjoecox — APPROVED** [review]
