### PR TITLE
[Enhancement] Adds fix to play correct audio when collecting the 4th piece of a heart container

### LINKED ISSUE #864: "Get a Heart Container!" Music Doesn't Play When Collecting 4th Heart Piece
- [x] I have checked checked the known issues and searched Github to ensure this issue has not already been reported.

### Description of the inaccuracy:
When you collect a 4th heart piece to fill a heart container, I expect to hear the "Get a Heart Container!" music rather than the "Small Item Catch" music that ordinarily plays when getting heart pieces 1-3.

### System Information:
- OS: Windows 11
- GFX Backend: DirectX
- Game Version: 1.1.1
- Rom Version: N64 USA

### Additional Information:
I was looking through the code and saw this in `z_player.c` which appears to imply that "Get a Heart Container!" should be playing when collecting the 4th container.
```
            if ((this->getItemId == GI_HEART_CONTAINER) ||
                ((this->getItemId == GI_HEART_PIECE) && EQ_MAX_QUEST_HEART_PIECE_COUNT)) {
                seqId = NA_BGM_GET_HEART | 0x900;
            }
```

### PR DESCRIPTION
**Pull request by lscholte**
Fix for https://github.com/HarbourMasters/2ship2harkinian/issues/864

This adds an optional bug fix to play the correct audio when collecting a 4th heart piece to fill a complete heart container.

### Build Artifacts
  - [2ship-linux.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/2199926700.zip)
  - [2ship-mac.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/2199927787.zip)
  - [2ship-windows.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/2199948819.zip)

### CODE REVIEW

File: mm/2s2h/Enhancements/Fixes/CompletedHeartContainerAudio.cpp [hunk 1]
```diff
@@ -0,0 +1,16 @@
+#include <libultraship/bridge.h>
+#include "2s2h/GameInteractor/GameInteractor.h"
+
+extern "C" {
+#include "variables.h"
+}
+
+void RegisterCompletedHeartContainerAudio() {
+    REGISTER_VB_SHOULD(VB_COMPLETED_HEART_CONTAINER_AUDIO_FIX, {
+        GetItemId getItemId = va_arg(args, GetItemId);
```
Comment (Archez) [inline mm/2s2h/Enhancements/Fixes/CompletedHeartContainerAudio.cpp]: With `va_arg()` you have to be careful what type you specify. The va_arg macro is sensitive to the size of the type passed in.
The first thing of note is that enum types like `GetItemId` should not be used. This is because not all platforms assign enums with the same "size". Usually enums will be 32bit, but Linux will make them smaller.
The second thing is that arguments passed into a variadic function will go through a "promotion" process. Specifically, smaller types like `bool`, `char`, `short` will be promoted to `int`.

As it is right now, this line will crash on Linux.

The `getItemId` from the Player is a `s16` (`short`), so you will need to parse it as a `s32`/`int` on the va_arg side. Then you can cast it into a `GetItemId`.

```suggestion
        GetItemId getItemId = (GetItemId)va_arg(args, int);
```

File: mm/2s2h/GameInteractor/GameInteractor.h [hunk 2]
```diff
@@ -72,6 +72,7 @@ typedef enum {
     VB_CHECK_HELD_ITEM_BUTTON_PRESS,
     VB_MAGIC_SPIN_ATTACK_CHECK_FORM,
     VB_TRANSFORM_THUNDER_MATRIX,
+    VB_COMPLETED_HEART_CONTAINER_AUDIO_FIX
```
Comment (Archez) [inline mm/2s2h/GameInteractor/GameInteractor.h]: The VB enums should be named in a way that conveys what the game is normally doing, one way to think about it is as if the game is asking a question "Should X Y Z".
I think we could have this as `VB_PLAY_HEART_CONTAINER_GET_FANFARE`

Also please add a trailing comma, so that others after this don't have to add it (leading to increased chance of merge conflicts)

File: mm/2s2h/BenGui/SearchableMenuItems.h [hunk 3]
```diff
@@ -1375,7 +1375,11 @@ void AddEnhancements() {
                 .widgetTooltip = "Fixes textures that normally overflow to be patched with the correct size or format",
                 .widgetType = WIDGET_CVAR_CHECKBOX,
                 .widgetOptions = { .defaultVariant = true },
-                .widgetCallback = [](widgetInfo& info) { GfxPatcher_ApplyOverflowTexturePatches(); } } } } });
+                .widgetCallback = [](widgetInfo& info) { GfxPatcher_ApplyOverflowTexturePatches(); } },
+              { "Fix Completed Heart Container Audio", "gEnhancements.Fixes.CompletedHeartContainerAudio",
+                "Fixes a bug resulting that results in the wrong audio playing upon receiving a 4th piece of heart to "
```
Comment (Archez) [inline mm/2s2h/BenGui/SearchableMenuItems.h]:
```suggestion
                "Fixes a bug that results in the wrong audio playing upon receiving a 4th piece of heart to "
```

File: mm/2s2h/BenGui/BenMenuBar.cpp [hunk 4]
```diff
@@ -611,6 +611,11 @@ void DrawEnhancementsMenu() {
                                     { .tooltip = "Fixes a bug that results in the Ikana Great Fairy fountain looking "
                                                  "green instead of yellow, this was fixed in the EU version" });
 
+            UIWidgets::CVarCheckbox("Fix Completed Heart Container Audio",
+                                    "gEnhancements.Fixes.CompletedHeartContainerAudio",
+                                    { .tooltip = "Fixes a bug resulting that results in the wrong audio playing upon "
```
Comment (Archez) [inline mm/2s2h/BenGui/BenMenuBar.cpp]:
```suggestion
                                    { .tooltip = "Fixes a bug that results in the wrong audio playing upon "
```

File: mm/2s2h/GameInteractor/GameInteractor.h (hunk 2 above)
Comment (lscholte) [reply mm/2s2h/GameInteractor/GameInteractor.h]: Thanks for the advice on the naming. That is helpful to know. I have made your suggested change.

I've also fixed the comma. I'm a bit surprised that the code formatter doesn't already take care of stuff like this.

File: mm/2s2h/Enhancements/Fixes/CompletedHeartContainerAudio.cpp (hunk 1 above)
Comment (lscholte) [reply mm/2s2h/Enhancements/Fixes/CompletedHeartContainerAudio.cpp]: Thank you. When I get the time, I will read more into variadic functions. I have made your suggested change. But I've been unable to test non-Windows versions of 2ship as I don't have setups for it.

**Review by Archez — APPROVED** [review]
Thanks for addressing the feedback, LGTM 👍
